- name: install active directory with sub features and management tools
  win_feature:
    name: AD-Domain-Services
    state: present
    include_sub_features: True
    include_management_tools: True

- name: install telnet client with sub features and management tools
  win_feature:
    name: Telnet-Client
    state: present
    include_sub_features: True
    include_management_tools: True
  register: active_directory_and_telnet_controllers

- name: reboot active directory and telnet feature requires it
  win_reboot:
  when: active_directory_and_telnet_controllers.reboot_required
